# plot_config_sns.yaml

context: 'notebook'
style: 'darkgrid'
palette: 'deep'  # 或者您可以使用自定义调色板

colors:
  background: '#FFFFFF'
  grid: '#E5E5E5'
  axis: '#333333'
  lines:
    - '#1f77b4'
    - '#ff7f0e'
    - '#2ca02c'
    - '#d62728'
    - '#9467bd'
    # 更多颜色...